export const badgeConfigs = [
  // === Learning (duplicates) =============
  {
    name: 'OpenStack',
    badgeText: 'Openstack',
    labelBgColor: 'f01742',
    logoColor: 'fff',
    logo: 'openstack',
    link: 'https://www.openstack.org/',
    group: 'learning',
  },
  {
    name: 'Ansible',
    badgeText: 'Ansible',
    labelBgColor: '1A1918',
    logoColor: 'ff',
    logo: 'ansible',
    link: 'https://www.ansible.com/',
    group: 'learning',
  },
  {
    name: 'Arduino',
    badgeText: 'Arduino',
    labelBgColor: '00979D',
    logoColor: 'fff',
    logo: 'Arduino',
    link: 'https://www.arduino.cc/',
    group: 'learning',
  },
  {
    name: 'Kubernetes',
    badgeText: 'kubernetes',
    labelBgColor: '326ce5',
    logoColor: 'fff',
    logo: 'kubernetes',
    link: 'https://kubernetes.io/',
    group: 'learning',
  },

  // === OS ================================
  {
    name: 'Arch Linux',
    badgeText: 'Arch Linux (for work)',
    labelBgColor: '1793D1',
    logoColor: 'fff',
    logo: 'arch-linux',
    link: '',
    group: 'os',
  },
  {
    name: 'Cent OS',
    badgeText: 'Cent OS (for servers)',
    labelBgColor: '002260',
    logoColor: 'fff',
    logo: 'centos',
    link: '',
    group: 'os',
  },
  {
    name: 'Windows',
    badgeText: 'Windows (for gaming)',
    labelBgColor: '0078D6',
    logoColor: 'fff',
    logo: 'windows',
    link: '',
    group: 'os',
  },

  // === IDEs, Automation, Programs ========
  {
    name: 'Gitlab CI',
    badgeText: 'gitlab ci',
    labelBgColor: '181717',
    logoColor: 'fff',
    logo: 'gitlab',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Visual Studio Code',
    badgeText: 'Visual Studio Code',
    labelBgColor: '0078d7',
    logoColor: 'fff',
    logo: 'visual-studio-code',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Affinity Photo',
    badgeText: 'Affinity Photo',
    labelBgColor: '7E4DD2',
    logoColor: 'fff',
    logo: 'affinity-photo',
    link: '',
    group: 'toolsPrograms',
  },

  // === Frameworks, Platforms, Libraries ==
  {
    name: 'Angular',
    badgeText: 'Angular',
    labelBgColor: 'DD0031',
    logoColor: 'fff',
    logo: 'angular',
    link: '',
    group: 'libs',
  },
  {
    name: 'Laravel',
    badgeText: 'Laravel',
    labelBgColor: 'FF2D20',
    logoColor: 'fff',
    logo: 'laravel',
    link: '',
    group: 'libs',
  },
  {
    name: 'NPM',
    badgeText: 'NPM',
    labelBgColor: '000000',
    logoColor: 'fff',
    logo: 'npm',
    link: '',
    group: 'libs',
  },
  {
    name: 'JWT',
    badgeText: 'JWT',
    labelBgColor: '000000',
    logoColor: 'fff',
    logo: 'JSON web tokens',
    link: '',
    group: 'libs',
  },
  {
    name: 'Bootstrap',
    badgeText: 'Bootstrap',
    labelBgColor: '563D7C',
    logoColor: 'fff',
    logo: 'bootstrap',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'Django',
    badgeText: 'Django',
    labelBgColor: '092E20',
    logoColor: 'fff',
    logo: 'django',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'Flutter',
    badgeText: 'Flutter',
    labelBgColor: '02569B',
    logoColor: 'fff',
    logo: 'Flutter',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'React',
    badgeText: 'React',
    labelBgColor: '20232a',
    logoColor: 'fff',
    logo: 'react',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'TensorFlow',
    badgeText: 'TensorFlow',
    labelBgColor: 'FF6F00',
    logoColor: 'fff',
    logo: 'TensorFlow',
    link: '',
    group: 'libs_planned',
  },

  // === Languages =========================
  {
    name: 'C#',
    badgeText: 'C#',
    labelBgColor: '239120',
    logoColor: 'fff',
    logo: 'c-sharp',
    link: '',
    group: 'languages',
  },
  {
    name: 'C++',
    badgeText: 'C++ (basics)',
    labelBgColor: '00599C',
    logoColor: 'fff',
    logo: 'c++',
    link: '',
    group: 'languages',
  },
  {
    name: 'C',
    badgeText: 'C (basics)',
    labelBgColor: '00599C',
    logoColor: 'fff',
    logo: 'c',
    link: '',
    group: 'languages',
  },
  {
    name: 'Java',
    badgeText: 'Java',
    labelBgColor: 'ED8B00',
    logoColor: 'fff',
    logo: 'java',
    link: '',
    group: 'languages',
  },
  {
    name: 'JavaScript',
    badgeText: 'JavaScript',
    labelBgColor: '323330',
    logoColor: 'F7DF1E',
    logo: 'javascript',
    link: '',
    group: 'languages',
  },
  {
    name: 'TypeScript',
    badgeText: 'TypeScript',
    labelBgColor: '007ACC',
    logoColor: 'fff',
    logo: 'typescript',
    link: '',
    group: 'languages',
  },
  {
    name: 'PHP',
    badgeText: 'PHP',
    labelBgColor: '777BB4',
    logoColor: 'fff',
    logo: 'php',
    link: '',
    group: 'languages',
  },
  {
    name: 'Python',
    badgeText: 'Python (basics)',
    labelBgColor: '3670A0',
    logoColor: 'ffdd54',
    logo: 'python',
    link: '',
    group: 'languages',
  },
  {
    name: 'Swift',
    badgeText: 'Swift',
    labelBgColor: 'F54A2A',
    logoColor: 'fff',
    logo: 'swift',
    link: '',
    group: 'languages_planned',
  },
  {
    name: 'Go',
    badgeText: 'Go',
    labelBgColor: '00ADD8',
    logoColor: 'fff',
    logo: 'go',
    link: '',
    group: 'languages_planned',
  },
  {
    name: 'Dart',
    badgeText: 'Dart',
    labelBgColor: '0175C2',
    logoColor: 'fff',
    logo: 'dart',
    link: '',
    group: 'languages_planned',
  },
];