export const badgeConfigs = [
  // === Learning (duplicates) =============
  {
    name: 'OpenStack',
    badgeText: 'Openstack',
    secondText: '',
    labelBgColor: 'f01742',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'openstack',
    link: 'https://www.openstack.org/',
    group: 'learning',
  },
  {
    name: 'Ansible',
    badgeText: 'Ansible',
    secondText: '',
    labelBgColor: '1A1918',
    logoBgColor: '',
    logoColor: 'ff',
    logo: 'ansible',
    link: 'https://www.ansible.com/',
    group: 'learning',
  },
  {
    name: 'Arduino',
    badgeText: 'Arduino',
    secondText: '',
    labelBgColor: '00979D',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'Arduino',
    link: 'https://www.arduino.cc/',
    group: 'learning',
  },
  {
    name: 'Kubernetes',
    badgeText: 'kubernetes',
    secondText: '',
    labelBgColor: '326ce5',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'kubernetes',
    link: 'https://kubernetes.io/',
    group: 'learning',
  },

  // === OS ================================
  {
    name: 'Arch Linux',
    badgeText: 'Arch Linux',
    secondText: '(for work)',
    labelBgColor: '1584bc',
    logoBgColor: '1793D1',
    logoColor: 'fff',
    logo: 'arch-linux',
    link: '',
    group: 'os',
  },
  {
    name: 'Cent OS',
    badgeText: 'Cent OS',
    secondText: '(for servers)',
    labelBgColor: '001b4d',
    logoBgColor: '002260',
    logoColor: 'fff',
    logo: 'centos',
    link: '',
    group: 'os',
  },
  {
    name: 'Windows',
    badgeText: 'Windows',
    secondText: '(for gaming)',
    labelBgColor: '006dc1',
    logoBgColor: '0078D6',
    logoColor: 'fff',
    logo: 'windows',
    link: '',
    group: 'os',
  },

  // === IDEs, Automation, Programs ========
  {
    name: 'Gitlab CI',
    badgeText: 'gitlab ci',
    secondText: '',
    labelBgColor: '181717',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'gitlab',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Drone CI',
    badgeText: 'Drone CI',
    secondText: '(basics)',
    labelBgColor: '1a1a1a',
    logoBgColor: '212121',
    logoColor: 'fff',
    logo: 'drone',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Docker',
    badgeText: 'Docker',
    secondText: '',
    labelBgColor: '0db7ed',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'docker',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Visual Studio Code',
    badgeText: 'Visual Studio Code',
    secondText: '',
    labelBgColor: '0078d7',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'visual-studio-code',
    link: '',
    group: 'toolsPrograms',
  },
  {
    name: 'Affinity Photo',
    badgeText: 'Affinity Photo',
    secondText: '',
    labelBgColor: '7E4DD2',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'affinity-photo',
    link: '',
    group: 'toolsPrograms',
  },

  // === Frameworks, Platforms, Libraries ==
  {
    name: 'Angular',
    badgeText: 'Angular',
    secondText: '',
    labelBgColor: 'DD0031',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'angular',
    link: '',
    group: 'libs',
  },
  {
    name: 'Laravel',
    badgeText: 'Laravel',
    secondText: '',
    labelBgColor: 'FF2D20',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'laravel',
    link: '',
    group: 'libs',
  },
  {
    name: 'NPM',
    badgeText: 'NPM',
    secondText: '',
    labelBgColor: '000000',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'npm',
    link: '',
    group: 'libs',
  },
  {
    name: 'JWT',
    badgeText: 'JWT',
    secondText: '',
    labelBgColor: '000000',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'JSON web tokens',
    link: '',
    group: 'libs',
  },
  {
    name: 'Bootstrap',
    badgeText: 'Bootstrap',
    secondText: '',
    labelBgColor: '563D7C',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'bootstrap',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'Django',
    badgeText: 'Django',
    secondText: '',
    labelBgColor: '092E20',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'django',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'Flutter',
    badgeText: 'Flutter',
    secondText: '',
    labelBgColor: '02569B',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'Flutter',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'React',
    badgeText: 'React',
    secondText: '',
    labelBgColor: '20232a',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'react',
    link: '',
    group: 'libs_planned',
  },
  {
    name: 'TensorFlow',
    badgeText: 'TensorFlow',
    secondText: '',
    labelBgColor: 'FF6F00',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'TensorFlow',
    link: '',
    group: 'libs_planned',
  },

  // === DBs ===============================
  {
    name: 'Postgres',
    badgeText: 'Postgres',
    secondText: '',
    labelBgColor: '316192',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'postgresql',
    link: '',
    group: 'dbs',
  },
  {
    name: 'MySQL',
    badgeText: 'MySQL',
    secondText: '',
    labelBgColor: '00000f',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'mysql',
    link: '',
    group: 'dbs',
  },
  {
    name: 'MongoDB',
    badgeText: 'MongoDB',
    secondText: '',
    labelBgColor: '4ea94b',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'mongodb',
    link: '',
    group: 'dbs',
  },
  {
    name: 'Redis',
    badgeText: 'Redis',
    secondText: '',
    labelBgColor: 'DD0031',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'redis',
    link: '',
    group: 'dbs',
  },

  // === Languages =========================
  {
    name: 'C#',
    badgeText: 'C#',
    secondText: '',
    labelBgColor: '239120',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'c-sharp',
    link: '',
    group: 'languages',
  },
  {
    name: 'C++',
    badgeText: 'C++',
    secondText: '(basics)',
    labelBgColor: '00467d',
    logoBgColor: '00599C',
    logoColor: 'fff',
    logo: 'c++',
    link: '',
    group: 'languages',
  },
  {
    name: 'C',
    badgeText: 'C',
    secondText: '(basics)',
    labelBgColor: '00467d',
    logoBgColor: '00599C',
    logoColor: 'fff',
    logo: 'c',
    link: '',
    group: 'languages',
  },
  {
    name: 'Java',
    badgeText: 'Java',
    secondText: '',
    labelBgColor: 'ED8B00',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'java',
    link: '',
    group: 'languages',
  },
  {
    name: 'JavaScript',
    badgeText: 'JavaScript',
    secondText: '',
    labelBgColor: '323330',
    logoBgColor: '',
    logoColor: 'F7DF1E',
    logo: 'javascript',
    link: '',
    group: 'languages',
  },
  {
    name: 'TypeScript',
    badgeText: 'TypeScript',
    secondText: '',
    labelBgColor: '007ACC',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'typescript',
    link: '',
    group: 'languages',
  },
  {
    name: 'PHP',
    badgeText: 'PHP',
    secondText: '',
    labelBgColor: '777BB4',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'php',
    link: '',
    group: 'languages',
  },
  {
    name: 'Python',
    badgeText: 'Python',
    secondText: '(basics)',
    labelBgColor: '316590',
    logoBgColor: '3670A0',
    logoColor: 'ffdd54',
    logo: 'python',
    link: '',
    group: 'languages',
  },
  {
    name: 'Swift',
    badgeText: 'Swift',
    secondText: '',
    labelBgColor: 'F54A2A',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'swift',
    link: '',
    group: 'languages_planned',
  },
  {
    name: 'Go',
    badgeText: 'Go',
    secondText: '',
    labelBgColor: '00ADD8',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'go',
    link: '',
    group: 'languages_planned',
  },
  {
    name: 'Dart',
    badgeText: 'Dart',
    secondText: '',
    labelBgColor: '0175C2',
    logoBgColor: '',
    logoColor: 'fff',
    logo: 'dart',
    link: '',
    group: 'languages_planned',
  },
];