name: Build README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master
        uses: actions/checkout@v2

      - name: Setup NodeJs 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache dependencies and build outputs to improve execution time
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: node index.js ${{secrets.BIRTH}}

      - name: Commit and push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}